### ISSUE TITLE
错误提示:Request failed with status code 404

### ISSUE THREAD

**Issue by Raudience** [lessroc/homework-system#2]
本人使用步骤：
下载https://github.com/lessroc/homework-system压缩包并解压，
pnpm install+pnpm serve安装依赖成功，运行成功，没有报错。
打开网页，登陆提示networkerro，请求的是一个远程地址，由于在项目中未找到后端项目，猜测项目不是前后端分离，所以把地址都改成了http://localhost:3100/，-如下图
![image](https://github.com/lessroc/homework-system/assets/52769726/ce229bed-4fd1-4b0d-8a7a-0a6f9d98487e)

-现在报错“错误提示:Request failed with status code 404”，-如下图，请问我现在应该怎么做😘😘
![image](https://github.com/lessroc/homework-system/assets/52769726/f051af45-78f0-4535-aba4-5601af21912f)

**Comment by lessroc** [comment]
这仅是一个示例, 没有后端代码, 目前是运行不起来的, 学习vben-admin用的。你要做什么呢？

**Comment by Raudience** [comment]
管理我们班的作业😢

**Comment by lessroc** [comment]
实际生产中还需要一套后端的接口，可根据你后端服务配套的接口参考[vue-vben-admin](https://github.com/vbenjs/vue-vben-admin)来开发实现适用于自己需求的管理系统。这个可能不太适合你的需求哦

**Comment by Raudience** [comment]
好的👌，感谢🙏
